name: currency converter app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dev-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Start server
        run: |
          npm run start &  # Or node index.js
          sleep 5

      - name: Expose server with ngrok
        run: ngrok http 3000

      - name: Run dev script
        run: npm run dev


      # Optional: run tests if you have any
      # - name: Run tests
      #   run: npm test

      

