name: Run Currency Converter App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can change to 16, 20, etc.

      - name: Install dependencies
        run: npm install

      - name: Run the app
        run: node index.js  # change to your entry file

      # Optional: run tests if you have any
      # - name: Run tests
      #   run: npm test
